config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'notes#index'

  namespace :notes do
    resources :searches, only: :index
  end

  resources :notes, except: :index do
    resources :comments, only: :create
  end

  resources :tags, only: [:index, :create, :show]
  resources :users, only: [:show, :index]

  post   '/like/:note_id' => 'likes#like',   as: 'like'
  delete '/like/:note_id' => 'likes#unlike', as: 'unlike'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :note
  belongs_to :user 
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :note
end

app/models/note.rb
class Note < ApplicationRecord
  validates :title, :content, presence: true
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :tag_notes, dependent: :destroy
  has_many :tags,  through:  :tag_notes
  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user

  def self.search(search)
    if search
      Note.where('title LIKE(?)', "%#{search}%")
    else
      Note.all
    end
  end

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_notes
  has_many :notes,  through:  :tag_notes
end

app/models/tag_note.rb
class TagNote < ApplicationRecord
  belongs_to :tag
  belongs_to :note
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :notes
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :like_notes, through: :likes, source: :note
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/notes/#{comment.note.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, note_id: params[:note_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_variables

  def like
    like = current_user.likes.new(note_id: @note.id)
    like.save
  end

  def unlike
    like = current_user.likes.find_by(note_id: @note.id)
    like.destroy
  end

  private

  def set_variables
    @note = Note.find(params[:note_id])
    @id_name = "#like-link-#{@note.id}"
    @id_heart = "#heart-#{@note.id}"
  end
end

app/controllers/notes/searches_controller.rb
class Notes::SearchesController < ApplicationController
  def index
    @notes = Note.search(params[:keyword])
    respond_to do |format|
      format.html
      format.json
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit]
  before_action :move_to_index, except: [:index, :show]
  protect_from_forgery except: :update

  def index
    @notes = Note.includes(user: :comments).order("created_at DESC").page(params[:page]).per(10)
  end

  def new
    @note = Note.new
    @tag = Tag.new
    @tags = Tag.all
  end

  def create
    Note.create(note_params)
    redirect_to root_path
  end

  def show
    # @user = User.find(1)
    # NoteMailer.send_when_update(@user).deliver
    @tags = Tag.all
    @comment = Comment.new
    @comments = @note.comments.includes(:user)
  end

  def edit  
  end

  def update
    note = Note.find(params[:id])
    note.update(note_params)
    redirect_to root_path(note.id)
  end

  def destroy
    note = Note.find(params[:id])
    note.destroy
    redirect_to root_path
  end

  

  private

  def note_params
    params.require(:note).permit(:title, :content, tag_ids: []).merge(user_id: current_user.id)
  end

  def set_note
    @note = Note.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tag = Tag.new
    @tags = Tag.all
  end

  def create
  Tag.create(tag_params)
    redirect_to  new_note_path
  end

  def show
    @tags = Tag.all
    @tag = Tag.find(params[:id])
    @notes = @tag.notes.page(params[:page]).per(10).order("created_at DESC")
  end

  private
  def tag_params
    params.require(:tag).permit(:name)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    # NoteMailer.send_when_update(current_user).deliver
    @user = User.find(params[:id])
    @notes = @user.notes.page(params[:page]).per(10).order("created_at DESC")
    @tags = Tag.all
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/markdown_helper.rb
module MarkdownHelper
  def markdown(content)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      space_after_headers: true,
      with_toc_data: true
    }

    extensions = {
      autolink:           true,
      no_intra_emphasis:  true,
      fenced_code_blocks: true,
      tables:             true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)
    markdown.render(content).html_safe
  end

  def toc(text)
    toc_option = {
      nesting_level: 2
    }

    toc_renderer = Redcarpet::Render::HTML_TOC.new
    toc = Redcarpet::Markdown.new(toc_renderer, toc_option)
    toc.render(text).html_safe
  end

end

app/helpers/notes/searches_helper.rb
module Notes::SearchesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/likes/_like_links.html.erb
<div class="like-link float-right m-1 text-danger" id="like-link-<%= note.id %>">
  <% if current_user.likes.find_by(note_id: note.id) %>
    <%= link_to unlike_path(note.id), method: :delete, remote: true do %>
        <div class = "iine__button text-danger">❤️<%= note.likes.count %></div>
    <% end %>
  <% else %>
    <%= link_to like_path(note.id), method: :post, remote: true do %>
        <div class = "iine__button text-danger">♡️<%= note.likes.count %></div>
    <% end %>
  <% end %>
</div>

app/views/likes/like.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like_links", note: @note  )) %>');
$("<%= @id_heart %>").removeClass('glyphicon-heart-empty');
$("<%= @id_heart %>").addClass('glyphicon-heart');

app/views/likes/unlike.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like_links", note: @note  )) %>');
$("<%= @id_heart %>").addClass('glyphicon-heart-empty');
$("<%= @id_heart %>").removeClass('glyphicon-heart');

app/views/notes/_note.html.erb
  <div class="post shadow p-3 mb-5 bg-light rounded">
    <p class="post__date float-right text-muted"> 
      <%= note.created_at.strftime("%Y年%m月%d日 %H時%M分") %>  
    </p>
    <div class="post__title">
      <%= link_to note.title, note_path(note.id), class: "post__title--btn h1 text-dark", method: :get %>
    </div>
  

    <div class="post__user-name  list-unstyled mt-2 float-right ">
      <ul class="post-list form-inline text-right my-0 mr-auto ml-10">
        <li class="text-muted ">投稿者:　</li>
        <li class="text-dark mr-3">
        <%= link_to note.user.nickname, user_path(note.user), class: "post__user-name--btn te text-dark" %>  
        </li>
        <li class="comment-count m-1">
          <i class="far fa-comment " aria-hidden="true"></i>
          <%= note.comments.count %>
        </li>
        <li>
          <%= render 'likes/like_links', note: note %>
        </li>
      </ul>
    </div>

    <div class="tag mt-2">
    <% note.tags.each do |tag| %>
      <%= link_to tag.name, tag_path(tag.id), class: "label btn btn-warning" %> 
    <% end %>
    </div>

  </div>

app/views/notes/edit.html.erb
<div class="content__title edit-title">
  投稿の編集
</div>
<%= form_with model: @note, class: :form, local: true do |form| %>
  <label class="edit">タイトル</label>
  <%= form.text_field :title, placeholder: :タイトル, class: 'form-control edit-title-font' %>
  <label class="edit">本文</label>
  <%= form.text_area  :content, placeholder: :ブログ本文, rows: 10, class: 'form-control input-lg edit-content-font'%>
  <%= form.submit '更新する', class: 'btn btn-outline-secondary form_btn mt-2 create center edit-btn' %>
<% end %>

app/views/notes/index.html.erb
<%# <nav class="navbar navbar-light bg-light">
  <form class="form-inline">
    <input class="form-control mr-sm-2" type="text" placeholder="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>
</nav> %>
  

<%= render @notes %>

<%= paginate(@notes) %>

app/views/notes/new.html.erb
<div class='container'>
  <h1 class='new'>新規投稿</h1>
    <div class='form-group'>
      <%= form_with model: @note, class: :form, local: true do |form| %>
        <%= form.text_field :title, placeholder: :タイトル, class: 'form-control', id: 'blog_title' %>
        <%= form.collection_check_boxes :tag_ids, Tag.all, :id, :name %>
        <div id='editor'>
        <%= form.text_area :content, placeholder: :本文, rows: 5, class: 'form-control', id: 'blog_diary', "v-model" => "input", name: "note[content]" %>
        <div v-html='input | marked'></div>
        <%= form.submit nil, class: 'btn btn-outline-secondary form_btn mt-2 create' %>
      <% end %>
    </div>
    <div class='form-group'>
      <%= form_with(model: @tag, local: true) do |form| %>
        <%= form.text_area :name, placeholder: "tagの追加", rows: "1",class: 'tagname form-control' %>
        <%= form.submit "追加",class: 'send form-control btn btn-outline-secondary form_btn' %>
      <% end %>
    </div>
</div>

<script type="text/javascript">
window.onload = function() {
new Vue({
el: '#editor',
data: {
input: '<%== j @note.content %>',
},
filters: {
marked: marked,
},
});
};
</script>

app/views/notes/searches/index.html.erb
<% @notes.each do |note| %>
   <%= render partial: "notes/note", locals: { note: note } %>
<% end %>

app/views/notes/show.html.erb
<div class="container">
  <div class="show-title">
    <%= @note.title %>
  </div>
  <% if user_signed_in? && current_user.id == @note.user_id %>
    <div class="postManage float-right">
      <%= link_to "編集", edit_note_path(@note.id), class: "postManage__edit btn btn-secondary" %>
      <%= link_to "削除", note_path(@note.id), method: :delete, class: "postManage__delete btn btn-secondary" %>
    </div>
  <% end %>
  <div class="text-main-box">
    <div class="text-left mt-5 text-main ">
      <%= markdown(@note.content).html_safe %>
    </div>
  </div>

  <div class="form-group text-center commentbox">
  <%# 　<form class="form-horizontal"> %>
      <div class="container text-center">
        <% if current_user %>
          <%= form_with(model: [@note, @comment], local: true, class:"form-comment") do |f|%>
            <%= f.text_area :content, placeholder: "コメントする", class: "comment-area form-control ",rows: "1" %>
            <%= f.submit "SEND" ,class: "send-btn form-control btn btn-outline-secondary form_btn mt-2 create center"%>
          <% end %>
        <% else %>
          <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
        <% end %>
      </div>
      <h5>コメント一覧</h5>
        <% if @comments %>
          <% @comments.each do |comment| %>
            <p class="comments-menu">
              <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
              <%= comment.content %>
            </p>
          <% end %>
        <% end %>
    </div>
  <%# </form> %>
</div>


  

app/views/tags/index.html.erb
<div class="container">
<h1>tag一覧</h1>

<% @tags.each do |tag| %>
  <div class="lists d-flex">
    <div class="lists__name">
      <%= link_to tag.name, tag_path(tag), method: :get, calass: "list__name--tag"  %>
    </div>
    <div class="lists__count">
      <%= tag.notes.count %>
    </div>
  </div>
<% end %>
</div>

app/views/tags/show.html.erb
<div class="postTitle">
  <%= @tag.name %>  tag一覧
</div>
<% @notes.each do |note| %>    
  <%= render partial: "notes/note", locals: { note: note } %>
<% end %>
<%= paginate(@notes) %>

app/views/users/index.html.erb
 <% @users.each do |user| %>
    <div class="memos">
      <div class="memo">
        <%= link_to user.nickname, user_path(user), method: :get  %>
      </div>
    <div class="tag-count">
      <%= user.notes.count %>
    </div>
    </div>
    <% end %>

app/views/users/show.html.erb
<div class="postTitle">
  <%= @user.nickname %>さんの投稿一覧
</div>
<% @notes.each do |note| %>    
  <%= render partial: "notes/note", locals: { note: note } %>
<% end %>
<%= paginate(@notes) %>