config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'notes#index'

  namespace :notes do
    resources :searches, only: :index
  end

  resources :notes, except: :index do
    resources :comments, only: :create
  end

  resources :tags, only: [:index, :create, :show]
  resources :users, only: [:show, :index]

  post   '/like/:note_id' => 'likes#like',   as: 'like'
  delete '/like/:note_id' => 'likes#unlike', as: 'unlike'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :note
  belongs_to :user 
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :note
end

app/models/note.rb
class Note < ApplicationRecord
  validates :title, :content, presence: true
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :tag_notes, dependent: :destroy
  has_many :tags,  through:  :tag_notes
  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user

  def self.search(search)
    if search
      Note.where('title LIKE(?)', "%#{search}%")
    else
      Note.all
    end
  end

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_notes
  has_many :notes,  through:  :tag_notes
end

app/models/tag_note.rb
class TagNote < ApplicationRecord
  belongs_to :tag
  belongs_to :note
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :notes
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :like_notes, through: :likes, source: :note
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/notes/#{comment.note.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, note_id: params[:note_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_variables

  def like
    like = current_user.likes.new(note_id: @note.id)
    like.save
  end

  def unlike
    like = current_user.likes.find_by(note_id: @note.id)
    like.destroy
  end

  private

  def set_variables
    @note = Note.find(params[:note_id])
    @id_name = "#like-link-#{@note.id}"
    @id_heart = "#heart-#{@note.id}"
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit]
  before_action :move_to_index, except: [:index, :show]
  protect_from_forgery except: :update

  def index
    @notes = Note.includes(user: :comments).order("created_at DESC").page(params[:page]).per(10)
  end

  def new
    @note = Note.new
    @tag = Tag.new
    @tags = Tag.all
  end

  def create
    Note.create(note_params)
    redirect_to root_path
  end

  def show
    # @user = User.find(1)
    # NoteMailer.send_when_update(@user).deliver
    @tags = Tag.all
    @comment = Comment.new
    @comments = @note.comments.includes(:user)
  end

  def edit  
  end

  def update
    note = Note.find(params[:id])
    note.update(note_params)
    redirect_to root_path(note.id)
  end

  def destroy
    note = Note.find(params[:id])
    note.destroy
    redirect_to root_path
  end

  

  private

  def note_params
    params.require(:note).permit(:title, :content, tag_ids: []).merge(user_id: current_user.id)
  end

  def set_note
    @note = Note.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tag = Tag.new
    @tags = Tag.all
  end

  def create
  Tag.create(tag_params)
    redirect_to  new_note_path
  end

  def show
    @tags = Tag.all
    @tag = Tag.find(params[:id])
    @notes = @tag.notes.page(params[:page]).per(10).order("created_at DESC")
  end

  private
  def tag_params
    params.require(:tag).permit(:name)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    # NoteMailer.send_when_update(current_user).deliver
    @user = User.find(params[:id])
    @notes = @user.notes.page(params[:page]).per(10).order("created_at DESC")
    @tags = Tag.all
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/markdown_helper.rb
module MarkdownHelper
  def markdown(content)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      space_after_headers: true,
      with_toc_data: true
    }

    extensions = {
      autolink:           true,
      no_intra_emphasis:  true,
      fenced_code_blocks: true,
      tables:             true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)
    markdown.render(content).html_safe
  end

  def toc(text)
    toc_option = {
      nesting_level: 2
    }

    toc_renderer = Redcarpet::Render::HTML_TOC.new
    toc = Redcarpet::Markdown.new(toc_renderer, toc_option)
    toc.render(text).html_safe
  end

end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewNote</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.10/vue.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.js'></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>
  
  <div class="header">
    <div class="menu">
      <% if user_signed_in? %>
        <%= link_to NewNote, root_path, method: :get, class: "menu__name" %>
        <%= link_to current_user.nickname, user_path(current_user), method: :get, class: "menu__name" %>
        <div class="menu__icon">
          <div class="menu__icon--cog">
            <%= link_to new_note_path, method: :get do %>
              <i class="fas fa-comment"></i>
            <% end %>
          </div>
          <div class="menu__icon--plus">
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fas fa-door-open"></i>
            <% end %>
          </div>
        </div>
      <% else %>
        <%= link_to "ゲスト", root_path, method: :get, class: "menu__name" %>
        <div class="menu__icon">
          <div class="menu__icon--cog">
            <%= link_to new_user_session_path do %>
              <i class="fas fa-plus"></i>
            <% end %>
          </div>
          <div class="menu__icon--plus">
            <%= link_to new_user_registration_path do %>
              <i class="fas fa-door-closed"></i>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
      <%= form_with(url: notes_searches_path, local: true, method: :get, class: "search-form form-inline") do |form| %>
        <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input form-control form-control-sm ml-3 w-75 mx-4 " %>
        <%= form.submit "検索", class: "btn-search btn-outline-dark my-2 my-sm-0 " %>
      <% end %>
  </div>

  


  

  <div class="left-content">
  </div>

  <div class="right-bar">
  </div>

  <div class="right-content">
    <div class="posts">
    <%= yield %>
  </div>
    </div>
  </body>
</html>